rails_root/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :survey_questions
  # Defines the root path route ("/")
  root 'home#index'

  get 'home/index'
  get 'about', to: 'about#index'

  # get 'survey', to: 'survey_responses#new', as: 'survey'
  # get 'survey/page/:page', to: 'survey_responses#survey', as: 'survey_page'

  resources :survey_responses
  # patch 'survey_responses', to: 'survey_responses#create', as: :patch_survey_response

  resources :survey_profiles
  resources :invitations, param: :token, only: [:create, :show] do
    collection do
      get :not_found
    end
  end

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout', as: :logout
  # test route for auth0
  get '/auth/test' => 'auth0#test'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

rails_root/app/models/survey_profile.rb
# frozen_string_literal: true

# This is the model for the SurveyProfile
class SurveyProfile < ApplicationRecord
  enum role: {
    Principal: 0,
    Teacher: 1,
    Superintendent: 2
  }
  has_many :responses,
           foreign_key: :profile_id,
           class_name: 'SurveyResponse',
           dependent: :destroy

  has_many :claimed_invitations, class_name: 'Invitation', foreign_key: 'claimed_by_id'
end

rails_root/app/controllers/survey_profiles_controller.rb
# frozen_string_literal: true

# Controller for the survey_profiles resource
class SurveyProfilesController < ApplicationController
  include Secured
  before_action :set_survey_profile, only: %i[show edit update destroy]

  # GET /survey_profiles or /survey_profiles.json
  def index
    @survey_profiles = SurveyProfile.all
  end

  # GET /survey_profiles/1 or /survey_profiles/1.json
  def show; end

  # GET /survey_profiles/new
  def new
    @survey_profile = SurveyProfile.new
  end

  # GET /survey_profiles/1/edit
  def edit; end

  # POST /survey_profiles or /survey_profiles.json
  def create
    if invalid_form? || non_unique_user?
      handle_invalid_form
    else
      create_survey_profile
    end
  end

  # PATCH/PUT /survey_profiles/1 or /survey_profiles/1.json
  def update
    # if anything in survey_profile_params is nil, then the form is invalid

    if survey_profile_params.values.any?(&:nil?)
      respond_to do |format|
        format.html do
          redirect_to edit_survey_profile_url(@survey_profile), notice: 'invalid form', status: :unprocessable_entity
        end
        format.json { render json: { error: 'invalid form' }, status: :unprocessable_entity }
      end

      # check if trying access a non-existing user_id
    elsif SurveyProfile.find_by(user_id: survey_profile_params[:user_id]).nil?
      respond_to do |format|
        format.html do
          redirect_to edit_survey_profile_url(@survey_profile), notice: 'user_id does not exist',
                                                                status: :unprocessable_entity
        end
        format.json { render json: { error: 'user_id does not exist' }, status: :unprocessable_entity }
      end

    else
      respond_to do |format|
        if @survey_profile.update(survey_profile_params)
          format.html do
            redirect_to survey_profile_url(@survey_profile), notice: 'Survey profile was successfully updated.'
          end
          format.json { render :show, status: :ok, location: @survey_profile }

        end
      end
    end
  end

  # DELETE /survey_profiles/1 or /survey_profiles/1.json
  def destroy
    @survey_profile.destroy!

    respond_to do |format|
      format.html { redirect_to survey_profiles_url, notice: 'Survey profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def create_survey_profile
    @survey_profile = SurveyProfile.new(survey_profile_params)
    @survey_profile.user_id = session[:userinfo]['sub']

    if session[:invitation] && claim_invitation
      # claim_invitation method will handle the redirect
    else
      respond_to do |format|
        if @survey_profile.save
          format.html { redirect_to root_url }
          format.json { render :show, status: :created, location: @survey_profile }
        end
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_survey_profile
    @survey_profile = SurveyProfile.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def survey_profile_params
    params.require(:survey_profile).permit(:user_id, :first_name, :last_name, :campus_name, :district_name, :role)
  end

  def invalid_form?
    survey_profile_params.values.any? { |value| value.nil? || value.empty? }
  end

  def non_unique_user?
    SurveyProfile.find_by(user_id: session[:userinfo]['sub'])
  end

  def handle_invalid_form
    respond_to do |format|
      format.html do
        redirect_to new_survey_profile_url, notice: 'invalid form', status: :unprocessable_entity
      end
      format.json { render json: { error: 'invalid form' }, status: :unprocessable_entity }
    end
  end

  def claim_invitation
    temporary_invitation_session_var = session[:invitation]

    if temporary_invitation_session_var && temporary_invitation_session_var['expiration'] > Time.now
      invitation = Invitation.find_by(id: temporary_invitation_session_var['from'])
      if invitation
        sharecode_from_invitation = invitation.parent_response.share_code
        # survey_profile = SurveyProfile.find_by(user_id: session[:userinfo]['sub'])
        new_response_to_fill = SurveyResponse.create(profile: @survey_profile, share_code: sharecode_from_invitation)
        invitation.update(claimed_by_id: @survey_profile.id, response_id: new_response_to_fill.id)
        redirect_to edit_survey_response_path(new_response_to_fill)
        return true
      end
    end

    session.delete(:invitation)
    false
  end
end

rails_root/app/helpers/survey_profiles_helper.rb
# frozen_string_literal: true

# Helper methods for the survey profiles controller
module SurveyProfilesHelper
  def full_name(survey_profile)
    "#{survey_profile.first_name} #{survey_profile.last_name}"
  end

  def campus_name(survey_profile)
    survey_profile.campus_name.to_s
  end

  def district_name(survey_profile)
    survey_profile.district_name.to_s
  end

  def get_survey_profile_id(user_id)
    survey_profile = SurveyProfile.find_by(user_id:)
    survey_profile.id
  end
end

rails_root/app/views/survey_profiles/_form.html.erb
<%= form_with(model: survey_profile, html: {class: "col-4 offset-4"}) do |form| %>
  <div class="row d-flex justify-content-center">
    <% if survey_profile.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(survey_profile.errors.count, "error") %> prohibited this survey_profile from being saved:</h2>
        <ul>
          <% survey_profile.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="mb-3">
      <%= form.label :first_name, style: "display: block;text-transform: uppercase;" %>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :last_name, style: "display: block;text-transform: uppercase;" %>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :campus_name, style: "display: block;text-transform: uppercase;" %>
      <%= form.text_field :campus_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :district_name, style: "display: block;text-transform: uppercase;" %>
      <%= form.text_field :district_name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :role, style: "display: block;text-transform: uppercase;" %>
      <%= form.select :role,['Principal', 'Teacher', 'Superintendent'], {prompt: 'Select a role'}, class: "form-select" %>
    </div>
    <div class="mb-3 text-center">
      <%= form.submit class: "btn btn-outline-primary" %>
    </div>
  </div>
<% end %>

rails_root/app/views/survey_profiles/_survey_profile.html.erb
<div class="row d-flex" id="<%= dom_id survey_profile %>">
  <div class="col-6">
    <table class="table" style="--bs-border-width: 0">
      <tbody>
        <tr>
          <td style="width: 25%"><strong style="text-transform: uppercase">First Name</strong></td>
          <td><%= survey_profile.first_name %></td>
        </tr>

        <tr>
          <td style="width: 25%"><strong style="text-transform: uppercase">Last Name</strong></td>
          <td><%= survey_profile.last_name %></td>
        </tr>

        <tr>
          <td style="width: 25%"><strong style="text-transform: uppercase">Campus</strong></td>
          <td><%= survey_profile.campus_name %></td>
        </tr>

        <tr>
          <td style="width: 25%"><strong style="text-transform: uppercase">District</strong></td>
          <td><%= survey_profile.district_name %></td>
        </tr>

        <tr>
          <td style="width: 25%"><strong style="text-transform: uppercase">Role</strong></td>
          <td><%= survey_profile.role %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

rails_root/app/views/survey_profiles/edit.html.erb
<h1>Editing survey profile</h1>

<%= render "form", survey_profile: @survey_profile %>

<br>

<div>
  <%= link_to "Show this survey profile", @survey_profile %> |
  <%= link_to "Back to survey profiles", survey_profiles_path %>
</div>

rails_root/app/views/survey_profiles/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Survey profiles</h1>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>User ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Campus Name</th>
        <th>District Name</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @survey_profiles.each do |survey_profile| %>
        <tr>
          <td><%= survey_profile.user_id %></td>
          <td><%= survey_profile.first_name %></td>
          <td><%= survey_profile.last_name %></td>
          <td><%= survey_profile.campus_name %></td>
          <td><%= survey_profile.district_name %></td>
          <td><%= survey_profile.role %></td>
          <td><%= link_to "Show", survey_profile %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New survey profile", new_survey_profile_path %>

rails_root/app/views/survey_profiles/new.html.erb
<h1 class="text-center">Profile</h1>
<div>
  <div>
    <%= render "form", survey_profile: @survey_profile %>
  </div>
</div>

rails_root/app/views/survey_profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @survey_profile %>

<div>
  <%= link_to "Edit this survey profile", edit_survey_profile_path(@survey_profile) %> |
  <%= link_to "Back to survey profiles", survey_profiles_path %>

  <%= button_to "Destroy this survey profile", @survey_profile, method: :delete %>
</div>