rails_root/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :survey_questions
  # Defines the root path route ("/")
  root 'home#index'

  get 'home/index'
  get 'about', to: 'about#index'

  # get 'survey', to: 'survey_responses#new', as: 'survey'
  # get 'survey/page/:page', to: 'survey_responses#survey', as: 'survey_page'

  resources :survey_responses
  # patch 'survey_responses', to: 'survey_responses#create', as: :patch_survey_response

  resources :survey_profiles
  resources :invitations, param: :token, only: [:create, :show] do
    collection do
      get :not_found
    end
  end

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout', as: :logout
  # test route for auth0
  get '/auth/test' => 'auth0#test'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

rails_root/app/models/survey_question.rb
# frozen_string_literal: true

# This is the model for the SurveyQuestion
class SurveyQuestion < ApplicationRecord
  validates :text, presence: true
end

rails_root/app/controllers/survey_questions_controller.rb
# frozen_string_literal: true

# This is the controller for the SurveyQuestions
class SurveyQuestionsController < ApplicationController
  before_action :set_survey_question, only: %i[show edit update destroy]

  # GET /survey_questions or /survey_questions.json
  def index
    @survey_questions = SurveyQuestion.all
  end

  # GET /survey_questions/1 or /survey_questions/1.json
  def show; end

  # GET /survey_questions/new
  def new
    @survey_question = SurveyQuestion.new
  end

  # GET /survey_questions/1/edit
  def edit; end

  # POST /survey_questions or /survey_questions.json
  def create
    @survey_question = SurveyQuestion.new(survey_question_params)

    respond_to do |format|
      if @survey_question.save
        format.html { redirect_to survey_question_url(@survey_question), notice: 'Survey question was successfully created.' }
        format.json { render :show, status: :created, location: @survey_question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_questions/1 or /survey_questions/1.json
  def update
    respond_to do |format|
      if @survey_question.update(survey_question_params)
        format.html { redirect_to survey_question_url(@survey_question), notice: 'Survey question was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey_question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_questions/1 or /survey_questions/1.json
  def destroy
    @survey_question.destroy!

    respond_to do |format|
      format.html { redirect_to survey_questions_url, notice: 'Survey question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_survey_question
    @survey_question = SurveyQuestion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def survey_question_params
    params.require(:survey_question).permit(:text, :explanation, :section)
  end
end

rails_root/app/helpers/survey_questions_helper.rb
# frozen_string_literal: true

# This is the helper for the SurveyQuestionsController
module SurveyQuestionsHelper
  # survey question helper functions
  # returns the question text
  def question_text(question)
    question.text
  end
end

rails_root/app/views/survey_questions/_form.html.erb
<%= form_with(model: survey_question) do |form| %>
  <% if survey_question.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(survey_question.errors.count, "error") %> prohibited this survey_question from being saved:</h2>

      <ul>
        <% survey_question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.label :explanation, style: "display: block" %>
    <%= form.text_area :explanation %>
  </div>

  <div>
    <%= form.label :section, style: "display: block" %>
    <%= form.text_field :section %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

rails_root/app/views/survey_questions/_survey_question.html.erb
<div id="<%= dom_id survey_question %>">
  <p>
    <strong>Question text:</strong>
    <%= survey_question.text %>
  </p>

  <p>
    <strong>Explanation:</strong>
    <%= survey_question.explanation %>
  </p>

  <p>
    <strong>Section:</strong>
    <%= survey_question.section %>
  </p>

</div>

rails_root/app/views/survey_questions/edit.html.erb
<h1>Editing survey question</h1>

<%= render "form", survey_question: @survey_question %>

<br>

<div>
  <%= link_to "Show this survey question", @survey_question %> |
  <%= link_to "Back to survey questions", survey_questions_path %>
</div>

rails_root/app/views/survey_questions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Survey questions</h1>

<div id="survey_questions">
  <% @survey_questions.each do |survey_question| %>
    <%= render survey_question %>
    <p>
      <%= link_to "Show this survey question", survey_question %>
    </p>
  <% end %>
</div>

<%= link_to "New survey question", new_survey_question_path %>

rails_root/app/views/survey_questions/new.html.erb
<h1>New survey question</h1>

<%= render "form", survey_question: @survey_question %>

<br>

<div>
  <%= link_to "Back to survey questions", survey_questions_path %>
</div>

rails_root/app/views/survey_questions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @survey_question %>

<div>
  <%= link_to "Edit this survey question", edit_survey_question_path(@survey_question) %> |
  <%= link_to "Back to survey questions", survey_questions_path %>

  <%= button_to "Destroy this survey question", @survey_question, method: :delete %>
</div>