rails_root/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :survey_questions
  # Defines the root path route ("/")
  root 'home#index'

  get 'home/index'
  get 'about', to: 'about#index'

  # get 'survey', to: 'survey_responses#new', as: 'survey'
  # get 'survey/page/:page', to: 'survey_responses#survey', as: 'survey_page'

  resources :survey_responses
  # patch 'survey_responses', to: 'survey_responses#create', as: :patch_survey_response

  resources :survey_profiles
  resources :invitations, param: :token, only: [:create, :show] do
    collection do
      get :not_found
    end
  end

  get '/auth/auth0/callback' => 'auth0#callback'
  get '/auth/failure' => 'auth0#failure'
  get '/auth/logout' => 'auth0#logout', as: :logout
  # test route for auth0
  get '/auth/test' => 'auth0#test'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

rails_root/app/views/layouts/_footer.html.erb
<footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
  <div class="col mb-3">
    <a href="https://education.tamu.edu/" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
      <!-- <svg class="bi me-2" width="40" height="32">
                <use xlink:href="#bootstrap" />
              </svg> -->
      School of Education & Human Development
    </a>
    <p class="text-body-secondary">&copy; 2024</p>
  </div>
  <div class="col mb-3">
  </div>
  
</footer>

rails_root/app/views/layouts/_header.html.erb
<nav id="main-header" class="navbar navbar-expand-lg navbar-light border-bottom" style="margin-bottom: 1rem;">
  <%# <%= link_to "School of Education & Human Development", 'https://education.tamu.edu/', class: "d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none" %>
  <div class="container-fluid">
    <div class="navbar-brand">
      <div class="c-logo-lockup c-logo-lockup_horizontal">
        <div class="c-logo-lockup-logo">
          <a href="https://www.tamu.edu/" aria-label="visit tamu.edu"><img src="https://dmc-assets.tamu.edu/pattern-library/logos/TAM-LogoBox.svg" alt="Texas A&amp;M University logo" /></a>
        </div>
        <div class="c-logo-lockup-wordmark">
          <a href="https://education.tamu.edu/">
            <p class="c-logo-lockup-wordmark-large">School of Education &amp; Development</p>
          </a>
          <a href="https://elrc.tamu.edu">
            <p class="c-logo-lockup-wordmark-small">Education Leadership Research Center</p>
          </a>
        </div>
      </div>
    </div>
    <ul class="nav">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link #{'active' if current_page?(root_path)}", aria: { current: "page" } %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link #{'active' if current_page?(about_path)}" %>
      </li>
      <li class="nav-item">
        <%# <%= link_to "Survey Responses", survey_responses_path, class: "nav-link #{'active' if current_page?(survey_responses_path)}" %>
      </li>
      <li class="nav-item">
        <%# <%= link_to "Survey Profiles", survey_profiles_path, class: "nav-link #{'active' if current_page?(survey_profiles_path)}" %>
      </li>
      <li class="nav-item">
        <% if session[:userinfo] %>
          <%= button_to 'Logout', root_url + '/auth/logout', method: :get, data: { turbo: false }, class: "nav-link" %>
        <% else %>
          <%= button_to 'Login', '/auth/auth0', method: :post, data: { turbo: false }, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

rails_root/app/views/layouts/application.html.erb
<!DOCTYPE html>

<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %>">
    <%= message %>
  </div>
<% end %>
<html>
  <head>
    <title>ELRC | Synergistic Leadership Theory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <style>
      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <%= render "layouts/header" %>

      <%= yield %>
      
      <%= render "layouts/footer" %>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"></script>
    </div>
  </body>
</html>